name: flutter_amazon_clone_bloc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  camera_camera: ^3.0.0
  carousel_slider: ^5.0.0
  cloudinary_public: ^0.23.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  file_picker: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_rating_bar: ^4.0.1
  go_router: ^14.4.1
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  path_provider: ^2.1.5
  pay: ^2.0.0
  rename: ^3.0.2
  shared_preferences: ^2.3.3
  syncfusion_flutter_charts: ^27.1.58
  coupon_uikit: ^0.2.1
  flutter_stripe: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/category_images/
    - assets/images/bottom_offers/
    - assets/images/bottom_nav_bar/
    - assets/images/product_quality_icons/
    - assets/images/cart_screen_icons/
    - assets/applepay.json
    - assets/gpay.json
